#!/bin/bash
#/ Usage: script/package [PLATFORM] [VERSION]
#/
#/ Builds distributable packages for licensed.
#/ Packages are of the form licensed-$VERSION-$PLATFORM-x64.tar.gz and contain a `./licensed` executable
#/ Built packages are placed in the <root>/pkg directory.
#/
#/ OPTIONS:
#/   [PLATFORM]        (optional, default to all platforms) platform to build exe for
#/   [VERSION]         (optional, default to current git branch or SHA1) version of licensed to build exe at
#/

set -e

PLATFORM=""
if [ -n "$1" ]; then
  PLATFORM=":$1"
fi

bundle exec rake "package$PLATFORM"
