# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "Alamofire", "5.4.3"
  pod "MaterialComponents/Buttons", "124.2.0"
  pod "MaterialComponents/Cards", "124.2.0"
  pod "Chatto", git: "https://github.com/badoo/Chatto", tag: "4.1.0"

  target 'iosTests' do
    inherit! :search_paths
    
    pod "lottie-ios", "3.3.0"
  end

end
