# frozen_string_literal: true
source "https://rubygems.org"

gem "semantic", "1.6.0"

group :ignore do
  gem "json", "2.1.0"
end

group :bundler do
  gem "bundler"
end

group :exclude do
  gem "i18n", "1.0.1"
end

group :development do
 gem "tzinfo", "1.2.5"
end

group :test do
 gem "minitest", "5.11.3"
end

gem "pathed-gem-fixture", path: "pathed-gem-fixture"

# verify https://github.com/github/licensed/issues/71
git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem "mini_racer"

# verify https://github.com/github/licensed/issues/153
gem "aws-sdk-core", "3.39.0"
