#!/bin/bash
set -e

if [ -z "$(which npm)" ]; then
  echo "npm is required." >&2
  exit 1
fi

# setup test fixtures
BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd $BASE_PATH/test/fixtures/npm
npm install --loglevel error
