name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  licensed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          bundler-cache: true

      - name: Build Gem
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          gem build *.gemspec

      - name: Verify Gem Version
        run: script/verify-gem-version

      - name: Set commit message
        id: commit
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "message=Auto-update license files for PR #${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          else
            echo "message=Auto-update license files" >> $GITHUB_OUTPUT
          fi

      - id: licensed_ci
        uses: licensee/licensed-ci@f1f6507544a9db25b0f4730230bfdf67a9c1bc90 # v1.12.1
        with:
          # override the command to use licensed built from this repo
          command: bundle exec licensed

          # changes made using GITHUB_TOKEN will not re-trigger this action.
          # see https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          # for additional details on GITHUB_TOKEN not re-triggering this action
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # the "push" workflow pushes license file updates to the target branch.
          # e.g. when the action is run on a pull request, changes are pushed to the pull request branch
          # see https://github.com/github/licensed-ci for more details
          workflow: push

          commit_message: |
            ${{ steps.commit.outputs.message }}

            Generated by https://github.com/licensee/licensed/blob/main/.github/workflows/licensed.yml
