#!/bin/bash
set -e

if [ -z "$(which bower)" ]; then
  echo "A local bower installation is required for bower development." >&2
  exit 127
fi

# setup test fixtures
BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd $BASE_PATH/test/fixtures/bower

if [ "$1" == "-f" ]; then
  find . -not -regex "\.*" -and -not -name "bower\.json" -print0 | xargs -0 rm -rf
fi

bower install
