#!/bin/bash
set -e

if [ -z "$(which bundle)" ]; then
  echo "A local bundler instalation is required for bundler development." >&2
  exit 127
fi

# setup test fixtures
BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd $BASE_PATH/test/fixtures/bundler

# unset any pre-existing gemfile when installing test fixtures
unset BUNDLE_GEMFILE

if [ "$1" == "-f" ]; then
  find . -not -regex "\.*" -and -not -name "Gemfile" -and -not \( -path ./pathed-gem-fixture -prune \) -print0 | xargs -0 rm -rf
fi

bundle install --path vendor/gems --without ignore
