#!/bin/bash
set -e

if [ -z "$(which npm)" ]; then
  echo "A local npm installation is required for npm development." >&2
  exit 127
fi

# setup test fixtures
BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd $BASE_PATH/test/fixtures/npm
npm install
