#!/bin/bash
set -e

if [ -z "$(which npm)" ]; then
  echo "A local npm installation is required for npm development." >&2
  exit 127
fi

# setup test fixtures
BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd $BASE_PATH/test/fixtures/npm

if [ "$1" == "-f" ]; then
  find . -not -regex "\.*" -and -not -name "package\.json" -print0 | xargs -0 rm -rf
fi

npm install

# setup test fixtures with missing dependencies
mkdir -p "${BASE_PATH}/test/fixtures/npm-missing"
cd "${BASE_PATH}/test/fixtures/npm-missing"
cp ../npm/package.json .

if [ "${1}" == "-f" ]; then
  find . -not -regex "\.*" -and -not -name "package\.json" -print0 | xargs -0 rm -rf
fi

npm install
rm -rf node_modules/glob
touch yarn.lock
