#!/bin/bash
set -e

if [ -z "$(which npm)" ]; then
  echo "A local npm installation is required for npm development." >&2
  exit 127
fi

# setup test fixtures
BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd $BASE_PATH/test/fixtures/npm

FORCE=""
if [ "$1" == "-f" ]; then
  FORCE=1
fi

if [ -n "$FORCE" ]; then
  find . -not -regex "\.*" -and -not -name "package\.json*" -print0 | xargs -0 rm -rf
fi

NPM_MAJOR_VERSION="$(npm -v | cut -d'.' -f1)"
if [ "$NPM_MAJOR_VERSION" -ge "7" ]; then
  # do no install peerDependencies in npm 7
  npm install --legacy-peer-deps
else
  npm install
fi
